litellm_settings:
  drop_params: True
  set_verbose: False
  vertex_project: "speedy-victory-336109"
  vertex_location: "asia-east1"

model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: vertex_ai/gemini-pro
      safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE
  - model_name: gemini-pro
    litellm_params:
      model: vertex_ai/gemini-pro
      safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE
  - model_name: gemini-pro-1.5
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-preview-0409
      safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE      
  - model_name: claude-3-sonnet
    litellm_params:
      model: vertex_ai/claude-3-sonnet@20240229       

general_settings: 
  master_key: pwm-123